# Use Node.js LTS version as base image
FROM node:20

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build

# Install serve to serve the production build
RUN npm install -g serve

# Serve the application
CMD ["serve", "-s", "build"]

# Expose port
EXPOSE 5173
